/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    OrderCard: typeof import('./../components/OrderCard.vue')['default']
    OrderStatus: typeof import('./../components/OrderStatus.vue')['default']
    TicketStatus: typeof import('./../components/TicketStatus.vue')['default']
    XcPrivacyPopup: typeof import('./../components/xc-privacy-popup/index.vue')['default']
  }
}
