/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/about/about" |
       "/pages-feedback/action-sheet/index" |
       "/pages-feedback/circle/index" |
       "/pages-feedback/count-down/index" |
       "/pages-feedback/count-to/index" |
       "/pages-feedback/drop-menu/index" |
       "/pages-feedback/floating-panel/index" |
       "/pages-feedback/keyboard/index" |
       "/pages-feedback/loading/index" |
       "/pages-feedback/message-box/index" |
       "/pages-feedback/notice-bar/index" |
       "/pages-feedback/notify/index" |
       "/pages-feedback/number-keyboard/index" |
       "/pages-feedback/overlay/index" |
       "/pages-feedback/progress/index" |
       "/pages-feedback/sort-button/index" |
       "/pages-feedback/status-tip/index" |
       "/pages-feedback/swipe-action/index" |
       "/pages-feedback/toast/index" |
       "/pages-feedback/tooltip/index" |
       "/pages-form/calendar/index" |
       "/pages-form/calendar-view/index" |
       "/pages-form/checkbox/index" |
       "/pages-form/col-picker/index" |
       "/pages-form/datetime-picker/index" |
       "/pages-form/datetime-picker-view/index" |
       "/pages-form/form/index" |
       "/pages-form/input/index" |
       "/pages-form/input-number/index" |
       "/pages-form/password-input/index" |
       "/pages-form/picker/index" |
       "/pages-form/picker-view/index" |
       "/pages-form/radio/index" |
       "/pages-form/rate/index" |
       "/pages-form/search/index" |
       "/pages-form/select-picker/index" |
       "/pages-form/signature/index" |
       "/pages-form/slider/index" |
       "/pages-form/switch/index" |
       "/pages-form/textarea/index" |
       "/pages-form/upload/index" |
       "/pages-nav/backtop/index" |
       "/pages-nav/index-bar/index" |
       "/pages-nav/navbar/index" |
       "/pages-nav/pagination/index" |
       "/pages-nav/popover/index" |
       "/pages-nav/segmented/index" |
       "/pages-nav/sidebar/index" |
       "/pages-nav/tabbar/index" |
       "/pages-nav/tabs/index" |
       "/pages-show/badge/index" |
       "/pages-show/card/index" |
       "/pages-show/cell/index" |
       "/pages-show/collapse/index" |
       "/pages-show/curtain/index" |
       "/pages-show/divider/index" |
       "/pages-show/gap/index" |
       "/pages-show/grid/index" |
       "/pages-show/img/index" |
       "/pages-show/img-cropper/index" |
       "/pages-show/loadmore/index" |
       "/pages-show/skeleton/index" |
       "/pages-show/steps/index" |
       "/pages-show/sticky/index" |
       "/pages-show/swiper/index" |
       "/pages-show/table/index" |
       "/pages-show/tag/index" |
       "/pages-show/watermark/index" |
       "/pages-widget/button/index" |
       "/pages-widget/config-provider/index" |
       "/pages-widget/fab/index" |
       "/pages-widget/icon/index" |
       "/pages-widget/layout/index" |
       "/pages-widget/popup/index" |
       "/pages-widget/resize/index" |
       "/pages-widget/text/index" |
       "/pages-widget/transition/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/about/about"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
